Models/PostgresMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FXPostgresMap.Models
{
    public class PostgresMessage
    {
        public string message { get; set; }
        public string topic { get; set; }
        public int offset { get; set; }
        public int partition { get; set; }
    }
}

Models/SFContact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FXPostgresMap.Models
{
    public class SFContact
    {
        public string masterrecordid { get; set; }
        public string sfid { get; set; }
        public string firstname { get; set; }
        public DateTime createddate { get; set; }
        public string cookieid__c { get; set; }
        public string name { get; set; }
        public DateTime systemmodstamp { get; set; }
        public bool isdeleted { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public int id { get; set; }
        public string _hc_err { get; set; }
        public bool responded_to_vip_survey__c { get; set; }
        public bool followed_vip_on_facebook__c { get; set; }
        public string eventsource__c { get; set; }
        public string accountid { get; set; }
        public bool entrolled_in_vip__c { get; set; }
        public bool browsed_vip_website__c { get; set; }
    }
}

Controllers/PostgresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using FXPostgresMap.Models;
using Npgsql;
using System.Text;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace FXPostgresMap.Controllers
{
    public class PostgresController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.ClientID = ConfigVars.Instance.clientID;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> ReadWebTrafficByClientID()
        {
            try
            {
                List<PostgresMessage> postgresMessages = new List<PostgresMessage>();
                using (var sqlCon = new NpgsqlConnection(ConfigVars.Instance.PostgresDBConnectionString))
                {
                    sqlCon.Open();
                    using (NpgsqlCommand cmd = new NpgsqlCommand(string.Format("select \"Offset\",\"Message\",\"Topic\",\"Partition\" from fxvip where \"Message\" like '%{0}%';", ConfigVars.Instance.clientID), sqlCon))
                    {
                        using (NpgsqlDataReader reader = cmd.ExecuteReader())
                        {
                            while (reader.HasRows)
                            {
                                while (reader.Read())
                                {
                                    PostgresMessage kafkaMessage = new PostgresMessage();
                                    kafkaMessage.offset = (int)reader["offset"];
                                    kafkaMessage.partition = (int)reader["partition"];
                                    kafkaMessage.topic = (string)reader["topic"];
                                    kafkaMessage.message = (string)reader["message"];
                                    postgresMessages.Add(kafkaMessage);
                                }

                                if (reader.NextResult() == false)
                                    break;
                            }
                        }
                    }

                    return Json(postgresMessages);
                }
            }
            catch (Exception exception)
            {
                return Json(null);
            }
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> FlagContactAsBrowser()
        {
            try
            {
                List<SFContact> sfContacts = new List<SFContact>();
                using (var sqlCon = new NpgsqlConnection(ConfigVars.Instance.PostgresDBConnectionString))
                {
                    sqlCon.Open();
                    using (NpgsqlCommand cmd = new NpgsqlCommand(string.Format("update salesforce.contact set browsed_vip_website__c=true where cookieid__c='{0}';", ConfigVars.Instance.clientID), sqlCon))
                    {
                        cmd.ExecuteNonQuery();
                    }
                }

                using (var sqlCon = new NpgsqlConnection(ConfigVars.Instance.PostgresDBConnectionString))
                {
                    sqlCon.Open();
                    using (NpgsqlCommand cmd = new NpgsqlCommand(string.Format("select * from salesforce.contact where cookieid__c='{0}' and browsed_vip_website__c=true;", ConfigVars.Instance.clientID), sqlCon))
                    {
                        using (NpgsqlDataReader reader = cmd.ExecuteReader())
                        {
                            while (reader.HasRows)
                            {
                                while (reader.Read())
                                {
                                    SFContact sfContact = new SFContact();
                                    sfContact.masterrecordid = reader["masterrecordid"].ToString();
                                    sfContact.sfid = reader["sfid"].ToString();
                                    sfContact.firstname = reader["firstname"].ToString();
                                    sfContact.createddate = (DateTime)reader["createddate"];
                                    sfContact.cookieid__c = reader["cookieid__c"].ToString();
                                    sfContact.name = reader["name"].ToString();
                                    sfContact.systemmodstamp = (DateTime)reader["systemmodstamp"];
                                    sfContact.isdeleted = (bool)reader["isdeleted"];
                                    sfContact.lastname = reader["lastname"].ToString();
                                    sfContact.email = reader["email"].ToString();
                                    sfContact.id = (int)reader["id"];
                                    sfContact._hc_err = reader["_hc_err"].ToString();
                                    sfContact.responded_to_vip_survey__c = (bool)reader["responded_to_vip_survey__c"];
                                    sfContact.followed_vip_on_facebook__c = (bool)reader["followed_vip_on_facebook__c"];
                                    sfContact.eventsource__c = reader["eventsource__c"].ToString();
                                    sfContact.accountid = reader["accountid"].ToString();
                                    sfContact.entrolled_in_vip__c = (bool)reader["enrolled_in_vip__c"];
                                    sfContact.browsed_vip_website__c = (bool)reader["browsed_vip_website__c"];
                                    sfContacts.Add(sfContact);
                                }

                                if (reader.NextResult() == false)
                                    break;
                            }
                        }
                    }

                    return Json(sfContacts);
                }
            }
            catch (Exception exception)
            {
                return Json(null);
            }
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> ResetWebFlagFor()
        {
            try
            {
                using (var sqlCon = new NpgsqlConnection(ConfigVars.Instance.PostgresDBConnectionString))
                {
                    sqlCon.Open();
                    using (NpgsqlCommand cmd = new NpgsqlCommand(string.Format("update salesforce.contact set browsed_vip_website__c=false where cookieid__c='{0}';", ConfigVars.Instance.clientID), sqlCon))
                    {
                        cmd.ExecuteNonQuery();
                    }
                }

                return Json("success");
            }
            catch (Exception exception)
            {
                return Json(null);
            }
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Views/Postgres/Index.cshtml
@{
    ViewData["Title"] = "Web Traffic";
}

<input type="hidden" id="clientID" value="@String.Format("{0}", ViewBag.ClientID)" />
<div class="container-fluid" style="padding:0px;margin-top:1%;">
    <div class="col-md-12" style="padding:0px;margin-top:2%;vertical-align:middle">
        <div class="col-md-5" style="padding:0px;">
            <p style="text-align:center;font-weight:bold;">Postgres (FX-VIP)</p>
            <div class="table-responsive" style="max-height:450px;overflow-y: auto;padding:0px;">
                <table id="postgresDataTable" class="table-bordered" style="width:100%;min-height:450px;"></table>
            </div>
            <p style="text-align:center;font-weight:bold;color:orange;margin-top:10px;" id="postgresMessage">&nbsp;</p>
        </div>
        <div class="col-md-2" style="height:400px;margin-top:13%;">
            <input id="btnReadWebTrafficByClientID" type="button" value="Read Postgres Web Traffic" class="btn-custom" style="width:100%;" />
            <input id="btnFlagContactAsBrowser" type="button" value="Flag Contact as Web VIP" class="btn-custom" style="width:100%;margin-top:10%;" />
            <input id="btnResetWebFlagFor" type="button" value="Reset Web VIP Flag" class="btn-custom" style="width:100%;margin-top:10%;" />
        </div>
        <div class="col-md-5" style="padding:0px">
            <p style="text-align:center;font-weight:bold;">Heroku Connect (salesforce.contact)</p>
            <div class="table-responsive" style="max-height:450px;overflow-y: auto;padding:0px;">
                <table id="herokuDataTable" class="table-bordered" style="width:100%;min-height:450px;"></table>
            </div>
            <p style="text-align:center;font-weight:bold;color:green;margin-top:10px;" id="herokuMessage">&nbsp;</p>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        var urlReadAction = '/Postgres/ReadWebTrafficByClientID';
        var urlFlagContactAsBrowserAction = '/Postgres/FlagContactAsBrowser';
        var urlResetWebFlagForAction = '/Postgres/ResetWebFlagFor';
        var isSentData = false;
        var startProcess, btnText, btnBgColor;
        var postgresMessage = [], SFContacts = [];

        $(function () {
            $('#spinner').hide();
            bindPostgresDataTable();
            bindContactDataTable(false);
            $('#btnReadWebTrafficByClientID').on('click', function (e) {
                setActiveButtonBG($(this));
                resetTrafficTable(true);
                resetTrafficTable(false);
                readPostgresMessage();
            });
            $('#btnFlagContactAsBrowser').on('click', function (e) {
                if (postgresMessage == undefined || (postgresMessage && postgresMessage.length == 0))
                    return;
                setActiveButtonBG($(this));
                resetTrafficTable(false);
                readSFContact();
            });
            $('#btnResetWebFlagFor').on('click', function (e) {
                if (SFContacts == undefined || (SFContacts && SFContacts.length == 0))
                    return;
                setActiveButtonBG($(this));
                resetTrafficTable(false);
                updatSFContact();
            });
        });

        function setActiveButtonBG(activeButton) {
            $('input[type=button]').each(function () {
                if ($(this).attr('id') == activeButton.attr('id'))
                    $(this).addClass('btn-custom2');
                else {
                    $(this).removeClass('btn-custom2');
                }
            })
        }

        function resetTrafficTable(isPostgres) {
            var trafficTable = isPostgres ? $('#postgresDataTable') : $('#herokuDataTable');
            trafficTable.find("tr").remove();
            trafficTable.append("<tr class='emptyrow'><td style='text-align:center;'>No Record Found</td></tr>");
            if (isPostgres)
                $('#postgresMessage').html('');
            else
                $('#herokuMessage').html('');
        }

        function bindPostgresDataTable() {
            var tableDataRow;
            var trafficTable = $('#postgresDataTable');
            trafficTable.find('tr').remove();
            tableDataRow = trafficTable.find("tr");
            if (postgresMessage && postgresMessage.length > 0) {
                for (var i = 0; i < postgresMessage.length; i++) {
                    if (postgresMessage[i].message) {
                        trafficTable.append("<tr><td style='border-bottom: 1px solid #ddd;'><div class='wrapword'>" + postgresMessage[i].message + "</div></td></tr>");
                        tableDataRow = trafficTable.find("tr");
                    }
                }
                $('#postgresMessage').html("Messages Digested by Postgres for Contact '" + $('#clientID').val() + "'");
            }

            if (tableDataRow.length == 0) {
                trafficTable.append("<tr class='emptyrow'><td style='text-align:center;'>No Record Found</td></tr>");
            }
        }

        function bindContactDataTable(isReset) {
            var tableDataRow;
            var trafficTable = $('#herokuDataTable');
            trafficTable.find('tr').remove();
            tableDataRow = trafficTable.find("tr");
            if (SFContacts && SFContacts.length > 0) {
                for (var i = 0; i < SFContacts.length; i++) {
                    if (SFContacts[i]) {
                        if (isReset)
                            SFContacts[i].browsed_vip_website__c = false;
                        trafficTable.append("<tr><td style='border-bottom: 1px solid #ddd;vertical-align:top;'><div class='wrapword'>" + JSON.stringify(SFContacts[i]) + "</div></td></tr>");
                        tableDataRow = trafficTable.find("tr");
                    }
                }
                if (isReset)
                    $('#herokuMessage').html("Salesforce VIP Web User flag being reset for Contact '" + $('#clientID').val() + "'");
                else
                    $('#herokuMessage').html("Salesforce VIP Web User flag being set for Contact '" + $('#clientID').val() + "'");
            }

            if (tableDataRow.length == 0) {
                trafficTable.append("<tr class='emptyrow'><td style='text-align:center;'>No Record Found</td></tr>");
            }
        }

        function readPostgresMessage() {
            postgresMessage = [];
            $('#spinner').show();
            $.post(urlReadAction, null, function (data) {
                $('#spinner').hide();
                postgresMessage = data;
                bindPostgresDataTable()
            });
        }

        function readSFContact() {
            $('#spinner').show();
            $.post(urlFlagContactAsBrowserAction, null, function (data) {
                $('#spinner').hide();
                SFContacts = data;
                bindContactDataTable(false)
            });
        }

        function updatSFContact() {
            $('#spinner').show();
            $.post(urlResetWebFlagForAction, null, function (data) {
                $('#spinner').hide();
                console.log(data);
                bindContactDataTable(true)
            });
        }
    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Postgres to Heroku Connect Sync</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style type="text/css">
        .container-full-screen {
            margin: 0 auto;
            width: 100%;
        }
    </style>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-full-screen">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="javascript:void(0);" class="navbar-brand">Heroku</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Postgres" asp-action="Index">Postgres to Heroku Connect Sync</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-full-screen body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - david@heroku.com</p>
        </footer>
    </div>
    <div id="spinner" style="display:block;"></div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#spinner').hide();
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>